import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[window]
opacity = 0.75
padding = { x = 5, y = 0 }
dynamic_padding = true

[font]

normal.family = "ComicMono Nerd Font"
bold.family = "ComicMono Nerd Font"
italic.family = "ComicMono Nerd Font"
bold_italic.family = "ComicMono Nerd Font"
size = 13.0
