return {
	-- { "nvim-treesitter/nvim-treesitter-context" },
	-- { "RRethy/vim-illuminate", event = { "BufReadPost", "BufWritePost", "BufNewFile" } },
	-- {
	-- 	"lukas-reineke/indent-blankline.nvim",
	-- 	main = "ibl",
	-- 	event = { "BufReadPost", "BufWritePost", "BufNewFile" },
	-- 	opts = {
	-- 		-- exclude = {
	-- 		-- 	filetypes = {
	-- 		-- 		"dashboard",
	-- 		-- 	},
	-- 		-- },
	-- 	},
	-- },
	-- {
	-- 	"tris203/precognition.nvim",
	-- 	opts = {},
	-- },
	-- {
	-- 	"rachartier/tiny-inline-diagnostic.nvim",
	-- 	event = "VeryLazy", -- Or `LspAttach`
	-- 	priority = 1000, -- needs to be loaded in first
	-- 	opts = {
	-- 		preset = "classic",
	-- 	},
	-- },
	-- {
	-- 	"nvim-telescope/telescope.nvim",
	-- 	tag = "0.1.8",
	-- 	dependencies = {
	-- 		"nvim-lua/plenary.nvim",
	-- 		"nvim-telescope/telescope-symbols.nvim",
	-- 		"adoyle-h/lsp-toggle.nvim",
	-- 		"keyvchan/telescope-find-pickers.nvim",
	-- 		"crispgm/telescope-heading.nvim",
	-- 		"debugloop/telescope-undo.nvim",
	-- 	},
	-- },
	-- {
	-- 	"linux-cultist/venv-selector.nvim",
	-- 	dependencies = {
	-- 		"neovim/nvim-lspconfig",
	-- 		{ "nvim-telescope/telescope.nvim", branch = "0.1.x", dependencies = { "nvim-lua/plenary.nvim" } },
	-- 	},
	-- 	-- lazy = false,
	-- 	branch = "regexp",
	-- 	opts = {},
	-- 	cmd = "VenvSelect",
	-- },
	-- {
	-- 	"nvim-neotest/neotest",
	-- 	dependencies = {
	-- 		"nvim-neotest/nvim-nio",
	-- 		"nvim-lua/plenary.nvim",
	-- 		"antoinemadec/FixCursorHold.nvim",
	-- 		"nvim-treesitter/nvim-treesitter",
	-- 	},
	-- },
}
