return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = { "VeryLazy" },
	opts_extend = { "ensure_installed" },
	opts = {
		highlight = { enable = true, disable = { "latex" } },
		indent = { enable = true, disable = { "latex" } },
		ensure_installed = {
			"bash",
			"css",
			"diff",
			"gdscript",
			"html",
			"comment",
			"http",
			"hyprlang",
			"java",
			"javascript",
			"jsdoc",
			"json",
			"jsonc",
			"kdl",
			"latex",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"norg",
			"nu",
			"printf",
			"python",
			"query",
			"regex",
			"rust",
			"svelte",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
		},
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
	end,
}
